import Foundation

/// Structured comparison of planned vs. actual block timing for a completed
/// event. Generated by `PostEventReportGenerator` once an event transitions
/// to `.completed`, then persisted on `EventModel.postEventReport`.
///
/// The struct is `Codable` so it can be JSON-encoded into the SwiftData
/// store via `EventModel.postEventReportData` and round-tripped through
/// CloudKit alongside the rest of the event payload. It is `Sendable` so
/// the report can be passed across actor boundaries to the PDF renderer
/// or shared via `ShareLink`.
public struct PostEventReport: Codable, Sendable, Equatable {

    /// One entry per `TimeBlockModel` on the event, in chronological
    /// order by planned start. Entries for blocks that were never marked
    /// complete carry `actualCompletion == nil` and contribute `0` to
    /// `totalDriftMinutes`.
    public var entries: [BlockReportEntry]

    /// Sum of all `deltaMinutes` across completed blocks only.
    /// Positive means the timeline drifted late overall; negative means
    /// it ran ahead of schedule.
    public var totalDriftMinutes: Int

    /// Count of all `ShiftRecord`s associated with the event — i.e. the
    /// number of times the user (or dependency engine) applied a shift
    /// during execution.
    public var totalShiftCount: Int

    /// Wall-clock time the report was generated. Useful for the PDF
    /// header and to detect stale reports if a block is reopened.
    public var generatedAt: Date

    public init(
        entries: [BlockReportEntry],
        totalDriftMinutes: Int,
        totalShiftCount: Int,
        generatedAt: Date
    ) {
        self.entries = entries
        self.totalDriftMinutes = totalDriftMinutes
        self.totalShiftCount = totalShiftCount
        self.generatedAt = generatedAt
    }
}

/// Per-block row in a `PostEventReport`.
public struct BlockReportEntry: Codable, Sendable, Equatable {

    /// `TimeBlockModel.id` for stable cross-referencing back into the
    /// timeline (e.g. so the PDF row can deep-link to the block).
    public var blockID: UUID

    /// Display title of the block at the moment the report was built.
    public var blockTitle: String

    /// `TimeBlockModel.originalStart` — the start time before any shifts
    /// were applied during execution.
    public var plannedStart: Date

    /// `TimeBlockModel.completedTime` — the wall-clock moment the block
    /// was marked `.completed`. `nil` when the block was never completed
    /// (cancelled, skipped, or the event ended early).
    public var actualCompletion: Date?

    /// Difference between `actualCompletion` and `plannedStart`, rounded
    /// to whole minutes. Positive = late, negative = early. Blocks with
    /// `actualCompletion == nil` carry a delta of `0`.
    public var deltaMinutes: Int

    public init(
        blockID: UUID,
        blockTitle: String,
        plannedStart: Date,
        actualCompletion: Date?,
        deltaMinutes: Int
    ) {
        self.blockID = blockID
        self.blockTitle = blockTitle
        self.plannedStart = plannedStart
        self.actualCompletion = actualCompletion
        self.deltaMinutes = deltaMinutes
    }
}
