import SwiftUI
import PDFKit
import SwiftData
import UniformTypeIdentifiers
import Models
import Services

/// Full-screen PDF preview of the exported timeline.
///
/// Renders the PDF generated by `PDFGenerator` inside a scrollable
/// `PDFView`. Works on both iPhone and iPad.
struct PDFExportPreviewView: View {

    let eventID: UUID

    @Query private var results: [EventModel]
    @State private var pdfData: Data?
    @State private var pdfFileURL: URL?
    @State private var isGenerating = true

    private var event: EventModel? { results.first }

    init(eventID: UUID) {
        self.eventID = eventID
        _results = Query(
            filter: #Predicate<EventModel> { $0.id == eventID }
        )
    }

    var body: some View {
        Group {
            if isGenerating {
                ProgressView(String(localized: "Generating PDF…"))
            } else if let pdfData {
                PDFKitView(data: pdfData)
                    .ignoresSafeArea(edges: .bottom)
                    .onDrag {
                        let provider = NSItemProvider()
                        guard let pdfFileURL else { return provider }
                        provider.registerFileRepresentation(
                            forTypeIdentifier: UTType.pdf.identifier,
                            fileOptions: [],
                            visibility: .all
                        ) { completion in
                            completion(pdfFileURL, false, nil)
                            return nil
                        }
                        provider.suggestedName = pdfFileURL.deletingPathExtension().lastPathComponent
                        return provider
                    }
            } else {
                ContentUnavailableView(
                    String(localized: "Unable to Generate PDF"),
                    systemImage: "exclamationmark.triangle"
                )
            }
        }
        .navigationTitle(String(localized: "Export Preview"))
        .navigationBarTitleDisplayMode(.inline)
        .toolbar {
            if let pdfFileURL {
                ToolbarItem(placement: .primaryAction) {
                    ShareLink(
                        item: pdfFileURL,
                        preview: SharePreview(
                            event?.title ?? "Timeline",
                            image: Image(systemName: "doc.richtext")
                        )
                    )
                    .accessibilityLabel(String(localized: "Share PDF"))
                }
            }
        }
        .task {
            await generatePDF()
        }
    }

    private func generatePDF() async {
        guard let event else {
            isGenerating = false
            return
        }
        #if os(iOS)
        let generator = PDFGenerator()
        let eventTitle = event.title

        let result: (data: Data, url: URL?)? = await Task.detached {
            let data = generator.generate(from: event)

            let sanitizedTitle = eventTitle
                .components(separatedBy: CharacterSet.alphanumerics.inverted)
                .joined(separator: "_")
            let fileName = "\(sanitizedTitle)_Timeline.pdf"
            let tempURL = FileManager.default.temporaryDirectory.appendingPathComponent(fileName)
            do {
                try data.write(to: tempURL, options: .atomic)
                return (data, tempURL)
            } catch {
                return (data, nil)
            }
        }.value

        if let result {
            pdfData = result.data
            pdfFileURL = result.url
            AnalyticsService.send(.pdfExported)
        }
        #endif
        isGenerating = false
    }
}

// MARK: - PDFKit UIViewRepresentable

private struct PDFKitView: UIViewRepresentable {

    let data: Data

    func makeUIView(context: Context) -> PDFView {
        let pdfView = PDFView()
        pdfView.autoScales = true
        pdfView.displayMode = .singlePageContinuous
        pdfView.displayDirection = .vertical
        pdfView.document = PDFDocument(data: data)
        return pdfView
    }

    func updateUIView(_ pdfView: PDFView, context: Context) {
        if pdfView.document?.dataRepresentation() != data {
            pdfView.document = PDFDocument(data: data)
        }
    }
}
