import SwiftUI
import PDFKit
import SwiftData
import Models
import Services

/// Full-screen PDF preview of the exported timeline.
///
/// Renders the PDF generated by `PDFGenerator` inside a scrollable
/// `PDFView`. Works on both iPhone and iPad.
struct PDFExportPreviewView: View {

    let eventID: UUID

    @Query private var results: [EventModel]
    @State private var pdfData: Data?
    @State private var pdfFileURL: URL?
    @State private var isGenerating = true

    private var event: EventModel? { results.first }

    init(eventID: UUID) {
        self.eventID = eventID
        _results = Query(
            filter: #Predicate<EventModel> { $0.id == eventID }
        )
    }

    var body: some View {
        Group {
            if isGenerating {
                ProgressView(String(localized: "Generating PDF…"))
            } else if let pdfData {
                PDFKitView(data: pdfData)
                    .ignoresSafeArea(edges: .bottom)
            } else {
                ContentUnavailableView(
                    String(localized: "Unable to Generate PDF"),
                    systemImage: "exclamationmark.triangle"
                )
            }
        }
        .navigationTitle(String(localized: "Export Preview"))
        .navigationBarTitleDisplayMode(.inline)
        .toolbar {
            if let pdfFileURL {
                ToolbarItem(placement: .primaryAction) {
                    ShareLink(
                        item: pdfFileURL,
                        preview: SharePreview(
                            event?.title ?? "Timeline",
                            image: Image(systemName: "doc.richtext")
                        )
                    )
                    .accessibilityLabel(String(localized: "Share PDF"))
                }
            }
        }
        .task {
            generatePDF()
        }
    }

    private func generatePDF() {
        guard let event else {
            isGenerating = false
            return
        }
        #if os(iOS)
        let generator = PDFGenerator()
        let data = generator.generate(from: event)
        pdfData = data

        // Write to a temporary file so ShareLink presents a proper .pdf
        // that works with AirDrop, email, Files, and Print.
        let sanitizedTitle = event.title
            .components(separatedBy: CharacterSet.alphanumerics.inverted)
            .joined(separator: "_")
        let fileName = "\(sanitizedTitle)_Timeline.pdf"
        let tempURL = FileManager.default.temporaryDirectory.appendingPathComponent(fileName)
        do {
            try data.write(to: tempURL, options: .atomic)
            pdfFileURL = tempURL
        } catch {
            // Share won't be available but preview still works
        }
        #endif
        isGenerating = false
    }
}

// MARK: - PDFKit UIViewRepresentable

private struct PDFKitView: UIViewRepresentable {

    let data: Data

    func makeUIView(context: Context) -> PDFView {
        let pdfView = PDFView()
        pdfView.autoScales = true
        pdfView.displayMode = .singlePageContinuous
        pdfView.displayDirection = .vertical
        pdfView.document = PDFDocument(data: data)
        return pdfView
    }

    func updateUIView(_ pdfView: PDFView, context: Context) {
        if pdfView.document?.dataRepresentation() != data {
            pdfView.document = PDFDocument(data: data)
        }
    }
}
