#!/bin/sh
# Xcode Cloud post-clone hook.
#
# Config/Secrets.xcconfig is intentionally gitignored (Supabase project refs +
# anon keys), so a fresh CI checkout doesn't have it and Debug/Release.xcconfig
# fail their #include. Recreate it here from the workflow's environment
# variables (App Store Connect → Xcode Cloud → workflow → Environment).
#
# Required variables (values come from your local Config/Secrets.xcconfig):
#   SUPABASE_DEV_REF, SUPABASE_DEV_ANON_KEY,
#   SUPABASE_PROD_REF, SUPABASE_PROD_ANON_KEY
set -e

: "${SUPABASE_DEV_REF:?Set SUPABASE_DEV_REF in the Xcode Cloud workflow environment}"
: "${SUPABASE_DEV_ANON_KEY:?Set SUPABASE_DEV_ANON_KEY in the Xcode Cloud workflow environment}"
: "${SUPABASE_PROD_REF:?Set SUPABASE_PROD_REF in the Xcode Cloud workflow environment}"
: "${SUPABASE_PROD_ANON_KEY:?Set SUPABASE_PROD_ANON_KEY in the Xcode Cloud workflow environment}"

SECRETS_PATH="$CI_PRIMARY_REPOSITORY_PATH/Config/Secrets.xcconfig"

cat > "$SECRETS_PATH" <<EOF
// Generated by ci_scripts/ci_post_clone.sh — values come from the Xcode Cloud
// workflow environment. Do not commit a real Secrets.xcconfig.
SUPABASE_DEV_REF = ${SUPABASE_DEV_REF}
SUPABASE_DEV_ANON_KEY = ${SUPABASE_DEV_ANON_KEY}
SUPABASE_PROD_REF = ${SUPABASE_PROD_REF}
SUPABASE_PROD_ANON_KEY = ${SUPABASE_PROD_ANON_KEY}
EOF

echo "Wrote $SECRETS_PATH"
